// Fix round 4: the reviewer probe harness (/private/tmp/pidbrr: prev/adv/adv2/fp) plus the round-4
// brief's extra cases, as one table. Paths/urls mirror the probe's own context.
import { describe, it, expect } from 'vitest';
import { guardDecision, type GuardContext } from '../src/agent/hooks/guard.js';

const ctx: GuardContext = {
  dataDir: '/home/u/.claude/plugins/data/pidb',
  written: ['/repo/.env', '/repo/config/db.env'],
  serverUrls: ['http://localhost:8080', 'https://pidb.example.com'],
  home: '/home/u',
  platform: 'linux',
};
const wctx: GuardContext = {
  dataDir: 'C:\\Users\\u\\.claude\\plugins\\data\\pidb',
  written: ['C:\\repo\\.env'],
  serverUrls: ['http://localhost:8080'],
  home: 'C:\\Users\\u',
  platform: 'win32',
  appData: 'C:\\Users\\u\\AppData\\Roaming',
};

type Row = [expected: 'DENY' | 'ALLOW', tool: string, input: Record<string, unknown>, win?: boolean];

function run(rows: Row[]): void {
  it.each(rows.map((r) => [`${r[0]} ${r[1]}${r[3] ? ' [win]' : ''} ${JSON.stringify(r[2])}`, r] as const))('%s', (_label, row) => {
    const [expected, tool, input, win] = row;
    const d = guardDecision({ hook_event_name: 'PreToolUse', cwd: win ? 'C:\\repo' : '/repo', tool_name: tool, tool_input: input }, win ? wctx : ctx);
    expect(d.deny ? 'DENY' : 'ALLOW').toBe(expected);
  });
}

describe('guard probe: prev (earlier rounds)', () => {
  run([
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'env | grep PIDB'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- bash -c \"printenv | sort\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'set | grep PIDB'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'export -p'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- env|grep PIDB"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- printenv|grep PIDB"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- node -pe 'process.env.PIDB_X'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- python3 -c 'import os;print(os.getenv(\"PIDB_X\"))'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- bash -c 'set -o posix; set'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- cat /proc/$$/environ"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- node -e \"console.log(process.env)\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- node -p \"process.env\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'echo $PIDB_PASSWORD'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- powershell -Command \"Get-ChildItem Env:\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- pwsh -c '$env:PIDB_X'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- cmd /c set"}],
  ["DENY", "Bash", {"command":"cd x\npidb login"}],
  ["DENY", "Bash", {"command":"npx pidb login"}],
  ["DENY", "Bash", {"command":"(pidb token list)"}],
  ["DENY", "Bash", {"command":"echo $(pidb secret get acme DB)"}],
  ["DENY", "Bash", {"command":"pidb secret get acme DB --print"}],
  ["DENY", "Bash", {"command":"echo hi && pidb login https://x"}],
  ["DENY", "Bash", {"command":"true; pidb token list"}],
  ["DENY", "Bash", {"command":"pidb.cmd login https://x"}],
  ["DENY", "Bash", {"command":"git add .env"}],
  ["DENY", "Bash", {"command":"git add /repo/config/db.env"}],
  ["DENY", "Bash", {"command":"cat .env*"}],
  ["DENY", "Bash", {"command":"grep -r DATABASE_URL"}],
  ["DENY", "Bash", {"command":"grep -r DATABASE_URL ."}],
  ["DENY", "Bash", {"command":"rg DATABASE_URL ."}],
  ["DENY", "Bash", {"command":"cd /repo && cat .env"}],
  ["DENY", "Bash", {"command":"cat .env"}],
  ["DENY", "Bash", {"command":"head -5 .env"}],
  ["DENY", "Bash", {"command":"cat ./.env"}],
  ["DENY", "Bash", {"command":"cat ../repo/.env"}],
  ["DENY", "Bash", {"command":"cat ~/.config/pidb/profiles.json"}],
  ["DENY", "Bash", {"command":"security find-generic-password -s pidb -w"}],
  ["DENY", "Bash", {"command":"curl http://localhost:8080/api/projects"}],
  ["DENY", "Bash", {"command":"curl 127.0.0.1:8080/api/projects"}],
  ["DENY", "Bash", {"command":"curl 'http://[::1]:8080/api/projects'"}],
  ["DENY", "Read", {"file_path":"/repo/.env"}],
  ["DENY", "Grep", {"pattern":"X","path":"/repo"}],
  ["DENY", "mcp__x__read", {"target":"/home/u/.config/pidb/profiles.json"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- cd env && npm test"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- python -m venv env"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- env FOO=bar npm test"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- npm run get-data"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- curl https://api.example.com/get"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- node scripts/get-users.js"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme \"get token\" -- npm test"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- ./deploy.sh --print-summary"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'cat schema.sql | psql \"postgresql://$PIDB_USER:$PIDB_PASSWORD@h/db\"'"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'psql \"postgres://$PIDB_USER:$PIDB_PASSWORD@db/app\"'"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'mysql -p\"$PIDB_PASSWORD\" app'"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'curl -u \"$PIDB_USER:$PIDB_PASSWORD\" https://api'"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec staging-env DB -- npm test"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- set -e"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- docker compose --env-file .env up"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- node --env-file=.env app.js"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- docker run --env DEBUG=1 image"}],
  ["ALLOW", "Bash", {"command":"git commit -m \"fix pidb login flow\""}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme \"API token\" -- npm test"}],
  ["ALLOW", "Bash", {"command":"curl -s localhost:3000/api | jq ."}],
  ["ALLOW", "Bash", {"command":"find . -name \"*.ts\" | head"}],
  ["ALLOW", "Bash", {"command":"du -sh . | tail -1"}],
  ["ALLOW", "Bash", {"command":"git add . && git commit -m x"}],
  ["ALLOW", "Bash", {"command":"sed -i '' \"s/a/b/\" src/x.ts"}],
  ["ALLOW", "Bash", {"command":"ls .. | head"}],
  ["ALLOW", "Bash", {"command":"cat .env.example"}],
  ["ALLOW", "Bash", {"command":"curl http://localhost:9090/x"}],
  ["ALLOW", "Glob", {"pattern":"**/*.ts"}],
  ["ALLOW", "Glob", {"pattern":"**/*","path":"/repo"}],
  ["ALLOW", "LS", {"path":"/repo"}],
  ["ALLOW", "Read", {"file_path":"/repo/src/x.ts"}],
  ["ALLOW", "Edit", {"file_path":"/repo/.gitignore","old_string":"a","new_string":".env"}],
  ["ALLOW", "Write", {"file_path":"/repo/notes.md","content":"see /repo/.env"}],
  ["ALLOW", "Grep", {"pattern":"/repo/.env","path":"/repo/src"}],
  ["ALLOW", "mcp__x__search", {"query":"","path":"."}],
  ["ALLOW", "mcp__x__list", {"dir":"/repo"}],
  ]);
});

describe('guard probe: adv (adversarial round 3)', () => {
  run([
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- bash -lc 'env'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- bash -lc \"printenv | grep PIDB\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- sh -ec 'echo $PIDB_PASSWORD'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- zsh -ic 'env'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- cmd /c \"echo %PIDB_PASSWORD%\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- cmd /c echo %PIDB_PASSWORD%"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- cmd.exe /C \"set PIDB\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- powershell -NoProfile -Command \"Write-Output $env:PIDB_PASSWORD\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- pwsh -NoProfile -c \"[Environment]::GetEnvironmentVariables()\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- pwsh -c \"gci env:PIDB_*\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- pwsh -c \"\\\"$env:PIDB_PASSWORD\\\"\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- pwsh -c \"dir env:\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- pwsh -c \"Get-Item env:PIDB_PASSWORD\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- pwsh -c \"$env:PIDB_PASSWORD | Out-Host\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- sudo -E env"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- env -0"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- env | sort"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- printenv PIDB_PASSWORD"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- echo \"$PIDB_PASSWORD\" | base64"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- printf '%s\\n' \"${PIDB_PASSWORD}\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'echo \"DB=$PIDB_PASSWORD\" >&2'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'echo $PIDB_PASSWORD | tee /tmp/p'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- sh -c \"printf %s \\\"$PIDB_PASSWORD\\\"\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'cat <<< \"$PIDB_PASSWORD\"'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- python -c \"import os; print(dict(os.environ))\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- python3 -c 'import os,json;print(json.dumps({k:v for k,v in os.environ.items() if k.startswith(\"PIDB\")}))'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- node -e 'console.log(JSON.stringify(process.env))'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- node --eval 'console.log(process.env.PIDB_PASSWORD)'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- bun -e 'console.log(process.env)'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- deno eval 'console.log(Deno.env.toObject())'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- ruby -e 'puts ENV[\"PIDB_PASSWORD\"]'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- perl -e 'print $ENV{PIDB_PASSWORD}'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- awk 'BEGIN{print ENVIRON[\"PIDB_PASSWORD\"]}'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- cat /proc/self/environ | tr '\\0' '\\n'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- declare -x"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- export"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- set -o posix; set"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- time env"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- xargs -0 -L1 -a /proc/self/environ"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- bash -c 'declare -p | grep PIDB'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- bash -c \"compgen -v | grep PIDB\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- pidb secret get acme X --print"}],
  ["DENY", "Bash", {"command":"./node_modules/.bin/pidb login https://x"}],
  ["DENY", "Bash", {"command":"node_modules/.bin/pidb token list"}],
  ["DENY", "Bash", {"command":"npm exec pidb login"}],
  ["DENY", "Bash", {"command":"pnpm pidb login"}],
  ["DENY", "Bash", {"command":"time pidb token list"}],
  ["DENY", "Bash", {"command":"bash -c 'pidb secret get acme DB --print'"}],
  ["DENY", "Bash", {"command":"x=$(pidb secret get acme DB --print); echo $x"}],
  ["DENY", "Bash", {"command":"echo `pidb token list`"}],
  ["DENY", "Bash", {"command":"pidb secret get \"acme\" \"DB\""}],
  ["DENY", "Bash", {"command":"bash -c 'cat .env'"}],
  ["DENY", "Bash", {"command":"sh -c \"grep PASSWORD .env\""}],
  ["DENY", "Bash", {"command":"cat \"/repo/.env\""}],
  ["DENY", "Bash", {"command":"cat '.env'"}],
  ["DENY", "Bash", {"command":"cat .env | head"}],
  ["DENY", "Bash", {"command":"less config/db.env"}],
  ["DENY", "Bash", {"command":"cd config && cat db.env"}],
  ["DENY", "Bash", {"command":"cd config; tail -n 3 *.env"}],
  ["DENY", "Bash", {"command":"grep -rn PASSWORD ."}],
  ["DENY", "Bash", {"command":"grep -R PASSWORD"}],
  ["DENY", "Bash", {"command":"rg -n PASSWORD"}],
  ["DENY", "Bash", {"command":"git grep PASSWORD"}],
  ["DENY", "Bash", {"command":"find . -name '*.env' -exec cat {} +"}],
  ["DENY", "Bash", {"command":"find . -name '*.env' | xargs cat"}],
  ["DENY", "Bash", {"command":"cp .env /tmp/leak"}],
  ["DENY", "Bash", {"command":"tar czf /tmp/x.tgz .env"}],
  ["DENY", "Bash", {"command":"source .env && npm test"}],
  ["DENY", "Bash", {"command":"set -a; . ./.env; set +a; npm test"}],
  ["DENY", "Bash", {"command":"diff .env .env.example"}],
  ["DENY", "Bash", {"command":"python -c \"print(open('.env').read())\""}],
  ["DENY", "Bash", {"command":"node -e \"console.log(require('fs').readFileSync('.env','utf8'))\""}],
  ["DENY", "Bash", {"command":"sort .env"}],
  // round-4 brief item 8: `wc` stays allowed (it only reveals a size) — deliberate deviation from the probe
  ["ALLOW", "Bash", {"command":"wc -c .env"}],
  ["DENY", "Bash", {"command":"git diff --no-index /dev/null .env"}],
  ["DENY", "Bash", {"command":"cat ~/.config/pidb/*"}],
  ["DENY", "Bash", {"command":"ls -la ~/.config/pidb && cat ~/.config/pidb/profiles.json"}],
  ["DENY", "Bash", {"command":"cat $HOME/.config/pidb/profiles.json"}],
  ["DENY", "Bash", {"command":"cat /home/u/.claude/plugins/data/pidb/written.json"}],
  ["DENY", "Bash", {"command":"jq . /home/u/.claude/plugins/data/pidb/profiles.json"}],
  ["DENY", "Bash", {"command":"security find-generic-password -s pidb -a default -w"}],
  ["DENY", "Bash", {"command":"python3 -c 'import keyring; print(keyring.get_password(\"pidb\",\"x\"))'"}],
  ["DENY", "Bash", {"command":"curl -s https://pidb.example.com/api/projects"}],
  ["DENY", "Bash", {"command":"wget -qO- http://127.0.0.1:8080/api/secrets"}],
  ["DENY", "Bash", {"command":"type %APPDATA%\\pidb\\profiles.json"}, true],
  ["DENY", "Bash", {"command":"type .env"}, true],
  ["DENY", "Bash", {"command":"Get-Content .\\.env"}, true],
  ["DENY", "Bash", {"command":"gc .env"}, true],
  ["DENY", "Bash", {"command":"Select-String -Path .env -Pattern PASS"}, true],
  ["DENY", "Bash", {"command":"findstr PASS .env"}, true],
  ["DENY", "Bash", {"command":"powershell -c \"Get-Content .env\""}, true],
  ["DENY", "Bash", {"command":"cmd /c type .env"}, true],
  ["DENY", "Bash", {"command":"Get-Content $env:APPDATA\\pidb\\profiles.json"}, true],
  ["DENY", "Bash", {"command":"cmdkey /list"}, true],
  ["DENY", "Bash", {"command":"Invoke-RestMethod http://localhost:8080/api/projects"}, true],
  ["DENY", "Bash", {"command":"irm http://localhost:8080/api/projects"}, true],
  ["DENY", "Read", {"file_path":".env"}],
  ["DENY", "Read", {"file_path":"/repo/config/../.env"}],
  ["DENY", "Read", {"file_path":"C:\\REPO\\.ENV"}, true],
  ["DENY", "Grep", {"pattern":"PASSWORD"}],
  ["DENY", "Grep", {"pattern":"PASSWORD","path":"."}],
  ["DENY", "Grep", {"pattern":"PASSWORD","path":"/"}],
  ["DENY", "Grep", {"pattern":"PASSWORD","path":"/repo/.env"}],
  ["DENY", "NotebookEdit", {"notebook_path":"/home/u/.config/pidb/x.ipynb"}],
  ["DENY", "mcp__plugin_serena_serena__read_file", {"relative_path":".env"}],
  ["DENY", "mcp__plugin_serena_serena__read_file", {"relative_path":"config/db.env"}],
  // round-4 brief item 14: '' and '.' are ignored for mcp__* (prev's `mcp__x__search {path: '.'}` must allow) — deliberate deviation
  ["ALLOW", "mcp__plugin_serena_serena__search_for_pattern", {"substring_pattern":"PASSWORD","relative_path":""}],
  ["DENY", "mcp__fs__read", {"path":"~/.config/pidb/profiles.json"}],
  ]);
});

describe('guard probe: adv2 (adversarial round 3b)', () => {
  run([
  ["DENY", "Bash", {"command":"export DB_PASS=\"$(pidb secret get acme DB --print)\""}],
  ["DENY", "Bash", {"command":"echo \"token: `pidb token list`\""}],
  ["DENY", "Bash", {"command":"psql \"postgres://u:$(pidb secret get acme DB --print)@h/db\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- sh -c \"echo $(printenv PIDB_PASSWORD)\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- echo \"$(env)\""}],
  ["DENY", "Bash", {"command":"cat \"$(pwd)/.env\""}],
  ["DENY", "Bash", {"command":"cat *.env"}],
  ["DENY", "Bash", {"command":"cat config/*.env"}],
  ["DENY", "Bash", {"command":"grep -r PASSWORD /"}],
  ["DENY", "Bash", {"command":"cat .env 2>/dev/null"}],
  ["DENY", "Bash", {"command":"cat .env>out.txt"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- printenv > /tmp/env.txt"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- env >&2"}],
  // probe row "@E\nenv" (the harness only substitutes "@E " with a trailing space): intended form below
  ["DENY", "Bash", {"command":"pidb secret exec acme DB --\nenv"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB --  env"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- 'env'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- /usr/bin/env"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- /bin/sh -c 'env'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- /usr/bin/printenv"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- command env"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- nohup env"}],
  ]);
});

describe('guard probe: fp (everyday dev work must stay allowed)', () => {
  run([
  ["ALLOW", "Bash", {"command":"rg TODO src"}],
  ["ALLOW", "Bash", {"command":"rg -n 'useState' src/components"}],
  ["ALLOW", "Bash", {"command":"grep -rn \"TODO\" src/"}],
  ["ALLOW", "Bash", {"command":"grep -r foo packages/cli/src"}],
  ["ALLOW", "Bash", {"command":"git grep -n foo -- src"}],
  ["ALLOW", "Bash", {"command":"find src -name '*.ts' -exec grep -l foo {} +"}],
  ["ALLOW", "Bash", {"command":"find src -name '*.ts' | xargs grep -l foo"}],
  ["ALLOW", "Bash", {"command":"ps aux | grep -v grep | grep node"}],
  ["ALLOW", "Bash", {"command":"git log --oneline | grep -i fix"}],
  ["ALLOW", "Bash", {"command":"npm test"}],
  ["ALLOW", "Bash", {"command":"npm run build && npm run typecheck"}],
  ["ALLOW", "Bash", {"command":"npm run type-check -- --pretty"}],
  ["ALLOW", "Bash", {"command":"git status && git diff"}],
  ["ALLOW", "Bash", {"command":"git add -A && git commit -m \"wip\""}],
  ["ALLOW", "Bash", {"command":"git add src/x.ts .gitignore"}],
  ["ALLOW", "Bash", {"command":"cat package.json | jq .scripts"}],
  ["ALLOW", "Bash", {"command":"cat README.md"}],
  ["ALLOW", "Bash", {"command":"head -50 src/index.ts"}],
  ["ALLOW", "Bash", {"command":"tail -f logs/app.log"}],
  ["ALLOW", "Bash", {"command":"sed -n 1,40p src/guard.ts"}],
  ["ALLOW", "Bash", {"command":"ls -la"}],
  ["ALLOW", "Bash", {"command":"ls -la ~"}],
  ["ALLOW", "Bash", {"command":"cd .. && ls"}],
  ["ALLOW", "Bash", {"command":"cd ~ && ls"}],
  ["ALLOW", "Bash", {"command":"tar czf dist.tgz dist"}],
  ["ALLOW", "Bash", {"command":"cp .env.example .env.local"}],
  ["ALLOW", "Bash", {"command":"mv src/a.ts src/b.ts"}],
  ["ALLOW", "Bash", {"command":"docker compose up -d && docker compose logs -f"}],
  ["ALLOW", "Bash", {"command":"curl -s https://api.github.com/repos/x/y | jq .stargazers_count"}],
  ["ALLOW", "Bash", {"command":"curl -s http://localhost:3000/health"}],
  ["ALLOW", "Bash", {"command":"node -e \"console.log(process.version)\""}],
  ["ALLOW", "Bash", {"command":"python3 -c 'import sys; print(sys.version)'"}],
  ["ALLOW", "Bash", {"command":"echo $PATH"}],
  ["ALLOW", "Bash", {"command":"env | grep NODE"}],
  ["ALLOW", "Bash", {"command":"printenv HOME"}],
  ["ALLOW", "Bash", {"command":"awk '{print $1}' access.log | sort | uniq -c"}],
  ["ALLOW", "Bash", {"command":"bash -c 'npm ci && npm test'"}],
  ["ALLOW", "Bash", {"command":"for f in src/*.ts; do wc -l \"$f\"; done"}],
  ["ALLOW", "Bash", {"command":"cat > /tmp/x.txt <<'EOF2'\nhello\nEOF2"}],
  ["ALLOW", "Bash", {"command":"vim src/x.ts"}],
  ["ALLOW", "Bash", {"command":"git commit -m \"docs: explain pidb token create and pidb secret get\""}],
  ["ALLOW", "Bash", {"command":"gh pr create --title \"Add pidb login docs\" --body \"run pidb login first\""}],
  ["ALLOW", "Bash", {"command":"echo 'run: pidb login https://x' >> NOTES.md"}],
  ["ALLOW", "Bash", {"command":"pidb secret write acme DB --out .env"}],
  ["ALLOW", "Bash", {"command":"pidb secret env acme DB --out .env.local"}],
  ["ALLOW", "Bash", {"command":"pidb projects list"}],
  ["ALLOW", "Bash", {"command":"pidb docs get acme readme"}],
  ["ALLOW", "Bash", {"command":"pidb secrets list acme"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- npx prisma migrate deploy"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'set -euo pipefail; npm run migrate'"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- bash -c 'export DATABASE_URL=\"postgres://$PIDB_USER:$PIDB_PASSWORD@db/app\" && npm run migrate'"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'DATABASE_URL=\"$PIDB_URL\" npx prisma db push'"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- env -u NODE_OPTIONS npm test"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- node -e \"require('./scripts/seed').run(process.env.PIDB_URL)\""}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- npm config set registry https://r"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- kubectl set image deploy/x x=img"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'echo \"migrating...\" && npm run migrate'"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- docker compose run --rm app npm test"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- terraform plan -var \"db_password=$PIDB_PASSWORD\""}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'echo done; psql \"$PIDB_URL\" -c \"select 1\"'"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- bash -c 'if [ -z \"$PIDB_PASSWORD\" ]; then echo missing; exit 1; fi; npm test'"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- sh -c 'test -n \"$PIDB_PASSWORD\" && echo ok'"}],
  ["ALLOW", "Bash", {"command":"npm test"}, true],
  ["ALLOW", "Bash", {"command":"Get-ChildItem -Recurse -Filter *.ts src"}, true],
  ["ALLOW", "Bash", {"command":"Get-Content package.json"}, true],
  ["ALLOW", "Bash", {"command":"type README.md"}, true],
  ["ALLOW", "Bash", {"command":"powershell -NoProfile -Command \"Get-Content package.json | ConvertFrom-Json\""}, true],
  ["ALLOW", "Bash", {"command":"cmd /c \"npm run build && npm test\""}, true],
  ["ALLOW", "Bash", {"command":"dir /s /b *.ts"}, true],
  ["ALLOW", "Bash", {"command":"$env:NODE_ENV='test'; npm test"}, true],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- powershell -c \"Invoke-Sqlcmd -Password $env:PIDB_PASSWORD -Query 'select 1'\""}, true],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- cmd /c \"npm run migrate\""}, true],
  ["ALLOW", "Bash", {"command":"Select-String -Path src\\*.ts -Pattern TODO"}, true],
  ["ALLOW", "Bash", {"command":"rg TODO src"}, true],
  ["ALLOW", "Grep", {"pattern":"TODO","path":"src"}],
  ["ALLOW", "Grep", {"pattern":"TODO","path":"/repo/src"}],
  ["ALLOW", "Glob", {"pattern":"**/.env*"}],
  ["ALLOW", "Glob", {"pattern":"*.env","path":"/repo/config"}],
  ["ALLOW", "LS", {"path":"/repo/config"}],
  ["ALLOW", "Read", {"file_path":"/repo/.env.example"}],
  ["ALLOW", "Read", {"file_path":"/repo/config/db.env.example"}],
  ["ALLOW", "Edit", {"file_path":"/repo/src/config.ts","old_string":"x","new_string":"readFileSync('/repo/.env')"}],
  ["ALLOW", "Write", {"file_path":"/repo/.env.example","content":"DB="}],
  ["ALLOW", "mcp__plugin_serena_serena__list_dir", {"relative_path":".","recursive":true}],
  ["ALLOW", "mcp__plugin_serena_serena__search_for_pattern", {"substring_pattern":"TODO","relative_path":"src"}],
  ["ALLOW", "mcp__plugin_serena_serena__find_symbol", {"name_path":"guardDecision","relative_path":"packages/cli/src/agent/hooks/guard.ts"}],
  ["ALLOW", "mcp__plugin_context7_context7__query-docs", {"libraryId":"/vercel/next.js","query":"app router"}],
  ["ALLOW", "mcp__fs__list", {"path":"/home/u/.config"}],
  ["ALLOW", "mcp__x__y", {"url":"https://example.com/a/b"}],
  ]);
});

describe('guard fix round 4: brief extras', () => {
  run([
  ["ALLOW", "Bash", {"command":"cat <<EOF > notes.md\npidb login is required\nEOF"}],
  ["ALLOW", "Bash", {"command":"cat <<-'EOF' > notes.md\n\tcat .env\n\tEOF\nnpm test"}],
  ["DENY", "Bash", {"command":"bash <<'EOF'\npidb login https://x\nEOF"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- sh <<EOF\nenv\nEOF"}],
  ["DENY", "Bash", {"command":"cat <<EOF > x\nhi\nEOF\ncat .env"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- node -e \"const c=require('pg');new c.Client(process.env.PIDB_URL).connect().then(()=>console.log('ok'))\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- node -e \"const c=1;console.log('url', process.env.PIDB_URL)\""}],
  ["ALLOW", "Bash", {"command":"git log -p -- src/x.ts"}],
  ["ALLOW", "Bash", {"command":"rg -t ts useEffect"}],
  ["ALLOW", "Bash", {"command":"rg -g '*.ts' foo"}],
  ["ALLOW", "Bash", {"command":"grep -rn --include='*.ts' foo ."}],
  ["ALLOW", "Bash", {"command":"diff <(ls a) <(ls b)"}],
  ["ALLOW", "Bash", {"command":"find . -name '.env*' -not -path './node_modules/*'"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- psql \"$PIDB_URL\" < migrations/001.sql"}],
  ["DENY", "Bash", {"command":"grep -r PASS *"}],
  ["DENY", "Bash", {"command":"grep -rn PASS config"}],
  ["DENY", "Bash", {"command":"eval \"$(pidb secret get acme DB --print)\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- zsh -c \"print -r -- $PIDB_PASSWORD\""}],
  ["DENY", "Bash", {"command":"cat \"$PWD/.env\""}],
  ["DENY", "Bash", {"command":"cat \"${PWD}/.env\""}],
  ["DENY", "Bash", {"command":"cat < .env"}],
  ["DENY", "Bash", {"command":"cat <.env"}],
  ["DENY", "Bash", {"command":"mysql app <.env"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- pidb secret get acme X --print"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- pwsh -c \"Write-Output \\\"$env:PIDB_X\\\"\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- pwsh -c \"echo \\\"$env:PIDB_X\\\"\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- Write-Output \"$env:PIDB_X\""}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- /usr/bin/env -0"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- bash -xc 'env'"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- env -i"}],
  ["DENY", "Bash", {"command":"pidb secret exec acme DB -- env -u FOO"}],
  ["DENY", "Bash", {"command":"bash -lc 'pidb login https://x'"}],
  ["DENY", "Bash", {"command":"cmd /c \"pidb token list\""}, true],
  ["DENY", "Bash", {"command":"sh -c 'cat config/*.env'"}],
  ["DENY", "Bash", {"command":"nl .env"}],
  ["DENY", "Bash", {"command":"tac .env"}],
  ["DENY", "Bash", {"command":"uniq .env"}],
  ["DENY", "Bash", {"command":"cmp .env .env.example"}],
  ["DENY", "Bash", {"command":"ruby -e 'puts File.read(\".env\")'"}],
  ["DENY", "Bash", {"command":"perl -ne 'print' .env"}],
  ["DENY", "Bash", {"command":"python3 -c \"print(open('db.env').read())\""}],
  ["DENY", "Bash", {"command":"deno eval \"console.log(Deno.readTextFileSync('.env'))\""}],
  ["DENY", "Bash", {"command":"curl.exe http://localhost:8080/api/projects"}, true],
  ["DENY", "Bash", {"command":"Invoke-WebRequest -Uri http://127.0.0.1:8080/api"}, true],
  ["DENY", "Bash", {"command":"http GET localhost:8080/api/projects"}],
  ["DENY", "Bash", {"command":"https pidb.example.com/api/projects"}],
  ["DENY", "Bash", {"command":"xh http://[::1]:8080/api/projects"}],
  ["DENY", "Bash", {"command":"wget2 -qO- http://localhost:8080/api"}],
  ["DENY", "Grep", {"pattern":"PASSWORD","path":"C:\\"}, true],
  ["DENY", "Grep", {"pattern":"PASSWORD"}, true],
  ["DENY", "Grep", {"pattern":"PASSWORD","glob":"*.env"}],
  ["DENY", "mcp__fs__read", {"file":".env"}],
  ["ALLOW", "Grep", {"pattern":"PASSWORD","glob":"*.ts"}],
  ["ALLOW", "Grep", {"pattern":"PASSWORD","type":"ts"}],
  ["ALLOW", "Grep", {"pattern":"PASSWORD","glob":"src/**"}],
  ["ALLOW", "Bash", {"command":"wc -l .env.example"}],
  ["ALLOW", "Bash", {"command":"wc -l src/*.ts"}],
  ["ALLOW", "Bash", {"command":"cat src/*.ts | wc -l"}],
  ["ALLOW", "Bash", {"command":"npm test 2>&1 | tail -20"}],
  ["ALLOW", "Bash", {"command":"node build.js > out.txt 2>&1"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- env -i PATH=/usr/bin npm test"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- /usr/bin/env node script.js"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- bash -lc 'npm run migrate'"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- time npm test"}],
  ["ALLOW", "Bash", {"command":"pidb secret exec acme DB -- nohup npm start"}],
  ["ALLOW", "Bash", {"command":"export NODE_ENV=production && npm run build"}],
  ["ALLOW", "Bash", {"command":"source ~/.nvm/nvm.sh && nvm use"}],
  ["ALLOW", "Bash", {"command":"diff src/a.ts src/b.ts"}],
  ["ALLOW", "Bash", {"command":"sort names.txt | uniq"}],
  ["ALLOW", "Bash", {"command":"python3 -c \"print(open('README.md').read())\""}],
  ["ALLOW", "Bash", {"command":"node -e \"console.log(require('./package.json').version)\""}],
  ["ALLOW", "Bash", {"command":"http GET https://api.github.com/repos/x/y"}],
  ["ALLOW", "Bash", {"command":"npx tsc --noEmit"}],
  ["ALLOW", "Bash", {"command":"pnpm test"}],
  ["ALLOW", "Bash", {"command":"yarn build"}],
  ["ALLOW", "Bash", {"command":"npm exec pidb projects list"}],
  ["ALLOW", "Bash", {"command":"find . -name '*.ts' | xargs wc -l"}],
  ["ALLOW", "Bash", {"command":"grep -rn TODO src test"}],
  ["ALLOW", "Bash", {"command":"git grep TODO -- '*.ts'"}],
  ["ALLOW", "mcp__fs__read", {"file":"src/index.ts"}],
  ["ALLOW", "mcp__x__y", {"query":"hello"}],
  ["ALLOW", "mcp__x__y", {"name":"guardDecision"}],
  ]);
});
